#!/bin/bash

echo "🔧 Configuration DNS pour silencut.com"
echo "======================================="
echo ""
echo "Une fois le domaine acheté, configure ces DNS :"
echo ""
echo "📍 ENREGISTREMENT A (pour le domaine principal)"
echo "   Type:   A"
echo "   Host:   @  (ou laisse vide)"
echo "   Points to: 75.2.60.5"
echo "   TTL:    600"
echo ""
echo "📍 ENREGISTREMENT CNAME (pour www)"
echo "   Type:   CNAME"
echo "   Host:   www"
echo "   Points to: silencut.onrender.com"
echo "   TTL:    600"
echo ""
echo "🔄 Ensuite sur Render :"
echo "1. Va sur: https://dashboard.render.com/web/srv-crfktmrtq21c73fmvi10/settings"
echo "2. Section 'Custom Domains'"
echo "3. Clique 'Add Custom Domain'"
echo "4. Entre: silencut.com"
echo "5. Clique 'Save'"
echo ""
echo "⏱️ Attendre 10-30 minutes pour la propagation DNS"
echo ""
echo "✅ Ton site sera accessible sur:"
echo "   https://silencut.com"
echo "   https://www.silencut.com"