#!/bin/bash

echo "🚀 Déploiement SilenCut sur Render"
echo ""
echo "📝 Instructions pour déployer:"
echo ""
echo "1. Va sur: https://dashboard.render.com/blueprints"
echo ""
echo "2. Clique sur 'New Blueprint Instance'"
echo ""
echo "3. Connecte ton compte GitHub si ce n'est pas déjà fait"
echo ""
echo "4. Entre cette URL:"
echo "   https://github.com/fred1433/silencut"
echo ""
echo "5. Clique sur 'Apply'"
echo ""
echo "✨ Ton app sera disponible sur:"
echo "   https://silencut.onrender.com"
echo ""
echo "Alternative rapide:"
echo "👉 Clique directement ici:"
echo "   https://render.com/deploy?repo=https://github.com/fred1433/silencut"
echo ""