services:
  - type: web
    name: silencut
    runtime: docker
    repo: https://github.com/fred1433/silencut
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true